phrase:
  access_token: 62c3a8049c6caf5f689d05e1ba1cc86d690478d11d3abaf2fc0430c6595907ec
  project_id: 31c462d344da4df7dd919604412c211d
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
